name: Push
on:
  push:
    branches:
      - main
      - develop

env:
  REPOSITORY: frozen-desserts
  IMAGE_TAG: latest

jobs:
  pipeline:
    name: Pipeline for build, test and deploy this service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push $REGISTRY/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
      - uses: addnab/docker-run-action@v3
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          image: $REGISTRY/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          options: -e RAILS_ENV=test -e LB_HOSTNAME=127.0.0.1
      - run: pip install -r ./pulumi/auto/requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ./pulumi/auto
          stack-name: dmaslovskaia/auto/${{ vars.ENV }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
